name: "Build validator image"
on:
  pull_request: # TODO: remove
  push:
    branches:
      - devnet
      - main

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  REPO_NAME: public.ecr.aws/g5z8o6h7/mamoru-aptos-fullnode/validator
  TARGET: validator

concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: furuensu
    steps:
      - uses: actions/checkout@v3

      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: public.ecr.aws
          username: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.8.2

      - name: Build and push validator image
        run: |
          TARGET_IMAGE_NAME="${{ env.REPO_NAME }}" \
          TARGET_IMAGE_TAG="${{ github.sha }}" \
          docker buildx bake --push --file docker/docker-bake-rust-all.hcl ${{ env.TARGET }}
