name: "Lint+Test"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet
      - testnet
      - aptos-release-*

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  CARGO_BUILD_JOBS: 16 # limit cargo jobs to by a single job
  CARGO_NET_GIT_FETCH_WITH_CLI: true

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  rust-lint:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
      - uses: ./.github/actions/rust-setup
      - run: cargo install cargo-sort --force
      - run: scripts/rust_lint.sh --check

  rust-doc-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
      - uses: ./.github/actions/rust-setup
      - run: cargo test --doc --workspace --exclude aptos-node-checker

  rust-unit-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
      - uses: ./.github/actions/rust-setup
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      - run: |
          cargo nextest run --profile ci --locked --workspace --retries 3 --no-fail-fast \
            --exclude smoke-test \
            --exclude aptos-testcases \
            --exclude generate-format \
            --exclude aptos-forge
        env:
          RUST_MIN_STACK: 4297152

  rust-smoke-test:
    runs-on: self-hosted
    needs: rust-unit-test
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - name: Prepare git and ssh config for build context
        run: |
          mkdir root-config
          cp -r ~/.gitconfig  ~/.ssh root-config/
      - uses: ./.github/actions/rust-setup
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      # prebuild node binary, so that tests don't start before node is built.
      - run: cargo build --bin=aptos-node --features=failpoints --release
      # --test-threads is intentionally set to reduce resource contention in ci jobs. Increasing this, increases job failures and retries.
      - run: LOCAL_SWARM_NODE_RELEASE=1 cargo nextest run --release --profile ci --package smoke-test --test-threads 3 --retries 3
