name: "Lint+Test"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  CARGO_BUILD_JOBS: 16 # limit cargo jobs to by a single job

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  rust-lint:
    runs-on: furuensu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-setup
      - run: cargo install cargo-sort
      - run: scripts/rust_lint.sh --check

  rust-doc-test:
    runs-on: furuensu
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: ./.github/actions/rust-setup
      - run: cargo test --doc --workspace --exclude aptos-node-checker

  rust-unit-test:
    runs-on: furuensu
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # get all the history because cargo xtest --change-since origin/main requires it.
      - uses: ./.github/actions/rust-setup
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      - run: cargo nextest run --profile ci --workspace --exclude smoke-test --exclude backup-cli --exclude testcases --retries 3 --no-fail-fast

  rust-smoke-test:
    runs-on: furuensu
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/rust-setup
      - uses: taiki-e/install-action@v1.5.6
        with:
          tool: nextest
      # prebuild node binary, so that tests don't start before node is built.
      - run: cargo build --bin=aptos-node --features=failpoints --release
      # --test-threads is intentionally set to reduce resource contention in ci jobs. Increasing this, increases job failures and retries.
      - run: LOCAL_SWARM_NODE_RELEASE=1 cargo nextest run --release --profile ci --package smoke-test --test-threads 3 --retries 5
      - name: Upload smoke test logs for failures
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: failed-smoke-test-logs
          # Retain all smoke test data except for the db (which may be large).
          path: |
            /tmp/.tmp*
            !/tmp/.tmp*/**/db/
          retention-days: 1

  slack-notify:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
      - rust-lint
      - rust-doc-test
      - rust-unit-test
      - rust-smoke-test
    steps:
    - uses: slackapi/slack-github-action@v1.22.0
      with:
        payload: |
          
          {
            "lint_conclusion": ${{ steps.rust-lint.conclusion == 'success' && "✅" || "❌" }},
            "doc_conclusion": ${{ steps.rust-doc-test.conclusion == 'success' && "✅" || "❌" }},
            "unit_conclusion": ${{ steps.rust-unit-test.conclusion == 'success' && "✅" || "❌" }},
            "smoke_conclusion": ${{ steps.rust-smoke-test.conclusion == 'success' && "✅" || "❌" }},
            "run_link": ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
