name: "Test slack"
on:
  pull_request:

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always
  CARGO_BUILD_JOBS: 16 # limit cargo jobs to by a single job

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  rust-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"

  slack-notify:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs:
      - rust-lint
    steps:
      - uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: |
            
            {
              "lint_conclusion": "${{ needs.rust-lint.result }}",
              "doc_conclusion":  "${{ needs.rust-lint.result }}",
              "unit_conclusion":  "${{ needs.rust-lint.result }}",
              "smoke_conclusion":  "${{ needs.rust-lint.result }}",
              "run_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
